repos:
  - repo: local
    hooks:
      - id: terraform-docs
        name: terraform-docs (inject README)
        entry: terraform-docs markdown table --output-file README.md --output-mode inject .
        language: system
        pass_filenames: false
        files: \\.tf$
